service: webinar-cloud-mock

package:
  patterns:
    - './**'

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
functions:
  main:
    handler: handler.handler
    timeout: 30
    events:
      - http:
          method: GET
          path: '/users'
          cors: true
